### ISSUE TITLE
Update to 1.21 Please

### ISSUE THREAD

**Issue by sternschnaube** [AdalynBlack/DynamicPistonVolume#1]
https://modrinth.com/mod/architectury-api/version/12.1.2+fabric

**Comment by AdalynBlack** [comment]
Hi, I'm working on this and trying to update as soon as possible, but Architectury currently has no information on the process of updating from 1.20.1 to 1.20.6. I have a working Fabric build now, but the Forge version is being problematic. A 1.20.6 version for both platforms should be available within the next 2 days unless further issues arise

**Comment by venaminecraft** [comment]
Great 😄

**Comment by AdalynBlack** [comment]
It turns out that Architectury currently doesn't work with Forge on 1.20.6. For the time being, I'll update the mod to support NeoForged for 1.20.6, and I'll keep an eye out for when Architectury officially supports 1.20.6 on Forge

**Comment by Rozbiynk** [comment]
any updates for 1.21?

**Comment by AdalynBlack** [comment]
Hi, apologies for the delays
Fabric works, but Forge is still being annoying, although for a different reason now. There's no good information on how to use NeoForge with Architectury
I'll release the Fabric version now, and once Forge works well on 1.21, I'll release an update for that as well

**Comment by AdalynBlack** [comment]
Ok, the 1.21 Fabric version is now available on Modrinth. I also realized that I had uploaded an empty jar for 1.20.1, and fixed that issue as well

**Comment by venaminecraft** [comment]
Thank you so much 😄
